name = "boltcard-poc"
main = "index.js"
compatibility_date = "2025-02-28"

kv_namespaces = [
  { binding = "UID_CONFIG", id = "7eaddc7f33d242ed94054dfb8da8fcbc" },
  { binding = "RATE_LIMITS", id = "RATE_LIMITS_KV_ID" }
]

[[durable_objects.bindings]]
name = "CARD_REPLAY"
class_name = "CardReplayDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CardReplayDO"]

routes = [
  "https://boltcardpoc.psbt.me/*"
]
