// Auto-generated by scripts/sync-js-exports.mjs — do not edit
export const BUILD_REVISION = "42f85a5";
export const JS_FINGERPRINT = "060fdad65dbc,114ffcaaf3ff,19c662710d1d,217b94f56238,27a4b8928b37,305920de266b,35e24f38ee2c,460689587e94,51aefb0201d3,65664854a4c3,6617b57907ac,68b7fc8c0fc8,8531031a09e3,8f945dcccc3d,947e97ea842d,adca0e73ca94,adf2fd9b9e21,af09975c2f5c,b768567c167e,e5ffce9a0873";
