// Auto-generated by scripts/sync-js-exports.mjs — do not edit
export const BUILD_REVISION = "5c2c840";
export const JS_FINGERPRINT = "27a4b8928b37,3c91b8660592,41e1cbc054f8,5117270eeb63,5d4333367688,65664854a4c3,789d4ae511f1,79dfa4f2cda9,7e3c240e9247,84e8b5eb92ca,86faac35c73a,8e4157fa574b,93d85fc50e1b,9a43a89754b4,9c1970f908eb,a3fcdd460afe,acb7eb5d907f,b5c22e50eb30,bf0c88d19b49,c4adfe7191d0,d2823720a078,d5223fbda65d,f8b81a160586";
