// Auto-generated by scripts/sync-js-exports.mjs — do not edit
export const BUILD_REVISION = "5eb1bba";
export const JS_FINGERPRINT = "02c9ea87e856,17a71e6f0a0e,1da706e9bede,21f4a9b9bfc4,27a4b8928b37,2aaf6cc28c88,3c91b8660592,41e1cbc054f8,5692b2d9d56f,5d4333367688,65664854a4c3,6cc60465ba90,733b34ef89d2,789d4ae511f1,79dfa4f2cda9,7e3c240e9247,84e8b5eb92ca,9a43a89754b4,9c1970f908eb,a0a95a055c4e,acb7eb5d907f,bf0c88d19b49,bf8ea35dd0c0,d041706ec4b1,d420b0ec9245,f559b75ad84f,f8b81a160586";
