// AUTO-GENERATED by scripts/build_keys.js — DO NOT EDIT
// Source: keys/*.csv
// Regenerate: node scripts/build_keys.js

export const ISSUER_KEYS_BY_DOMAIN = {
  "_default": [
    {
      "hex": "00000000000000000000000000000000",
      "label": "all-zeros"
    },
    {
      "hex": "00000000000000000000000000000001",
      "label": "dev-01"
    }
  ],
  "boltcardpoc.psbt.me": [
    {
      "hex": "b0733959686c5da274123084b5c07820",
      "label": "boltpoc-1"
    },
    {
      "hex": "0a276206ccae41739b3541e285223eee",
      "label": "boltpoc-2"
    },
    {
      "hex": "55734571ce72ed364994cf2f20914092",
      "label": "boltpoc-3"
    }
  ]
};

export const PERCARD_KEYS = [
  {
    "uid": "040a69fa967380",
    "k0": "d6672015edcef27c2615e76be0f3f4a2",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "ce08c57983d65fceaa571e248390790f",
    "card_name": ""
  },
  {
    "uid": "040c66fa967380",
    "k0": "6f36be36647e9ee251da4cd8e2a03ada",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "420e18a161fec00e083aaaa787fb3a3f",
    "card_name": ""
  },
  {
    "uid": "040e5ffa967380",
    "k0": "e73ab6b20ab98618920a0844ab076535",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "33219df9e785173f5d05d03cdc75e27b",
    "card_name": ""
  },
  {
    "uid": "04105ffa967380",
    "k0": "7983650b08f22f2bf8acac0ac0b45301",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "f8212c6b70173da52f18a81d8bf29457",
    "card_name": ""
  },
  {
    "uid": "04116ffa967380",
    "k0": "4b8a2e0042980c2afbbdb0440f0518b1",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "e35b18a891596550927b4d3b7eee1814",
    "card_name": ""
  },
  {
    "uid": "041379aac11390",
    "k0": "3f37b78ff2fac05bf4df2d09b5e3ee1d",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "1bd77ff4e5b0462f0f708bc570540342",
    "card_name": ""
  },
  {
    "uid": "0414607a8f6980",
    "k0": "b2a091d9a1359f8aabb44b1c30e671e5",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "8d1bd19b65ae35f1e3d4894cd1548337",
    "card_name": ""
  },
  {
    "uid": "041470fa967380",
    "k0": "f468adcfd1ec0a505f48d994d78f9b9c",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "d367349b7a4e37ffdc0051345602b1a7",
    "card_name": ""
  },
  {
    "uid": "0418607a8f6980",
    "k0": "c96c2c60a09249028896cae4ae4b84e2",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "09e45a3279644b2c20842a9f3e5651ac",
    "card_name": ""
  },
  {
    "uid": "04186dfa967380",
    "k0": "796d4b1267b12c0f62cafed3d05421db",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "4e088f2b1af48f2ac46a618010370e9e",
    "card_name": ""
  },
  {
    "uid": "04186ffa967380",
    "k0": "4f53cc46cfbc815eb85ab3bbb5463720",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "e04ecf202fc7cfc5b06db40fcb94133e",
    "card_name": ""
  },
  {
    "uid": "041b66fa967380",
    "k0": "4c825b6d8353018f20fe8d2438d37cf2",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "6f996fec58e5bff81919aeccbbf3a398",
    "card_name": ""
  },
  {
    "uid": "04245ffa967380",
    "k0": "c4fa41eaa3c80deb9979b7fa32e1a799",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "a94d26750a51634fe8e60b9a5b5ae982",
    "card_name": ""
  },
  {
    "uid": "042669fa967380",
    "k0": "7dde52e4ff6fceb8cdd91dcf2563e021",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "6513dd928144a72d49107c19ce3907c5",
    "card_name": ""
  },
  {
    "uid": "042966fa967380",
    "k0": "f8b13758205db6b9aa20dec04dea5318",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "bd7323d90d7d17c4e26a752b229bbff8",
    "card_name": ""
  },
  {
    "uid": "04339132151990",
    "k0": "f21103b0eeee186ddf3672aa61d04867",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "f5b89a8a724ae17bac70b7733433279d",
    "card_name": ""
  },
  {
    "uid": "043e607a8f6980",
    "k0": "0b2fd312e8d688ad5c87f53bf9ca1fe9",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "f030fc66668415e1b2ca4c8fda22dc6f",
    "card_name": ""
  },
  {
    "uid": "04426ffa967380",
    "k0": "bcd23e3ae6d41b1dfff1aa65dfd41dfa",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "8b92e9cc49cdeaf23499d804bc938eba",
    "card_name": ""
  },
  {
    "uid": "044275fa967380",
    "k0": "c6d5b3326fe1260032586151aa118dce",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "962fe4dce8c5b8328132e3ed91d5c68d",
    "card_name": ""
  },
  {
    "uid": "044475fa967380",
    "k0": "7c99f6eeecc0ed0ba2e9b762d5559255",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "b8c7b858fa15986db455843ad0af69f3",
    "card_name": ""
  },
  {
    "uid": "04475efa967380",
    "k0": "e214429bcd7f78c830d033a1b8798e6b",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "811ef2c6cff4b7e1f8c63088ca5d5a9c",
    "card_name": ""
  },
  {
    "uid": "04485efa967380",
    "k0": "fdc2dfa457fbe60d65683b0e8340ee31",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "87e12d6ddcd021b43bfdb6acd6638197",
    "card_name": ""
  },
  {
    "uid": "044a64fa967380",
    "k0": "57f5f47accb9078977f94867c3418235",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "a8c243a08a623569fb933cd375a2970f",
    "card_name": ""
  },
  {
    "uid": "045065fa967380",
    "k0": "7cf4831a7cf5a7320631b849f419d6d2",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "d4107fac3d1fd8dcaf3dcdbe8f421b75",
    "card_name": ""
  },
  {
    "uid": "0451607a8f6980",
    "k0": "c568996eadaf811aba1d503ddbd9241f",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "a883747710dbf843e363ae333d5c8fa7",
    "card_name": ""
  },
  {
    "uid": "045164fa967380",
    "k0": "125cd42fd757451fc93dd628166d73d4",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "562baa63329aa41fe4f21f398ef47005",
    "card_name": ""
  },
  {
    "uid": "0452607a8f6980",
    "k0": "c24500eef47d3a0d9c048cf3eb7a8bdf",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "584f27969f9c21944dc65e8e3fdb098b",
    "card_name": ""
  },
  {
    "uid": "045262fa967380",
    "k0": "605f02dd2190db0b559d2f5a19e91a95",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "5604280737be3143c581faa03c41ef51",
    "card_name": ""
  },
  {
    "uid": "045275fa967380",
    "k0": "0c4d6328ec4d78df4d30c77106aea58d",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "926ba2276101831a727c1ce12a22f7f8",
    "card_name": ""
  },
  {
    "uid": "045365fa967380",
    "k0": "55b0a6219a4173907dabad1ea2330dc6",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "4fce7f0c5cc01da51667946320ee072f",
    "card_name": ""
  },
  {
    "uid": "0455607a8f6980",
    "k0": "9b3a1ebca2d494b8f60719a6911e9c3c",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "bd11c4669bdcf630cbe301f20c11622d",
    "card_name": ""
  },
  {
    "uid": "045564fa967380",
    "k0": "39bf948967b9b6605b07bd398c80dde6",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "11c29f224b330bb6828d2ace45adeaee",
    "card_name": ""
  },
  {
    "uid": "04585efa967380",
    "k0": "fbf2f63fa9364eab7ea30704f2816cbb",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "495007077aadeae55c1740eb1b67415f",
    "card_name": ""
  },
  {
    "uid": "045862fa967380",
    "k0": "731c0eb9aca80c62167ecc29834369bf",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "fef5136e11daf5ac59cced35a6cdd460",
    "card_name": ""
  },
  {
    "uid": "045a607a8f6980",
    "k0": "081ca469f1cbdd8cc6a6fbc94c747685",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "1d00af13c44aa2b1285f9d79c74eeec9",
    "card_name": ""
  },
  {
    "uid": "045a75fa967380",
    "k0": "08c04a665d821689b22e58b4e1c2a7f9",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "595d567f1171381c2a6e89189bf094d4",
    "card_name": ""
  },
  {
    "uid": "045e607a8f6980",
    "k0": "71acc28977e1e85a962eb873cbbd3fa1",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "a0ce65e9f010fb59eb0d55c18ca1ccf1",
    "card_name": ""
  },
  {
    "uid": "0466607a8f6980",
    "k0": "c871358ffb42fed932cff283e5353b9c",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "13724702a454e174de898fab20d14ad0",
    "card_name": ""
  },
  {
    "uid": "046775fa967380",
    "k0": "6054323d82c6ca1cc1e006b148f9a9fd",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "9b06b4834a1d49c8fa03a8a8100e9024",
    "card_name": ""
  },
  {
    "uid": "046a64fa967380",
    "k0": "eb0371c8342f4b25258f927fa9e72687",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "a579818023f2dff74084c5e003755c22",
    "card_name": ""
  },
  {
    "uid": "046a65fa967380",
    "k0": "249d509c3d41c9b396028d6e23bfc5f7",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "265734823811524198f190fb2c53b9d7",
    "card_name": ""
  },
  {
    "uid": "046b64fa967380",
    "k0": "1d4965b93823b6b999af7c2deb411b9e",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "32255aafad016cf5440917c7326a08d7",
    "card_name": ""
  },
  {
    "uid": "046c607a8f6980",
    "k0": "7e8b4bfb239a6951c28d356450792bc0",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "593a7644ec87250da32f97cd8026de68",
    "card_name": ""
  },
  {
    "uid": "046f62fa967380",
    "k0": "58ab7b68538c48871ce6bc06861939dd",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "7b177bf49967ad62d4da1c2bdee599dc",
    "card_name": ""
  },
  {
    "uid": "046f65fa967380",
    "k0": "07d8ddaef558e3c1d4b7260e8280d27a",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "f1401a4be82a15d3f8068fb3cf0bb32b",
    "card_name": ""
  },
  {
    "uid": "0473607a8f6980",
    "k0": "0e7bac1ee9912022a4e0e16e3491d91b",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "470ad0e940b7cab5a04f027c3219edac",
    "card_name": ""
  },
  {
    "uid": "047362fa967380",
    "k0": "8f1b85d054053f6d6f7771d457e756cb",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "407285f181177c057252dc8b8eea2293",
    "card_name": ""
  },
  {
    "uid": "047462fa967380",
    "k0": "9bc40e6365c83d8d12136cf6c370f06e",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "13fa94c08ba415e56556060b5ea45db7",
    "card_name": ""
  },
  {
    "uid": "0475607a8f6980",
    "k0": "8f3330a59889887db5a3f4341d1c9e97",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "0f7f9ab245d971f4ed0afe34442ecc40",
    "card_name": ""
  },
  {
    "uid": "047565fa967380",
    "k0": "c469bdeee93a2241120516e3315eaa53",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "312e707b7f11e4b62670e42e5c6fff91",
    "card_name": ""
  },
  {
    "uid": "0476607a8f6980",
    "k0": "1c64ac7169a3871fc70e8ba21c89f203",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "99313cf9778cac41177d9e8faa673dee",
    "card_name": ""
  },
  {
    "uid": "047a6efa967380",
    "k0": "3c418c1581e32588f6781bb574d03840",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "82809b3cc5c977d3222736eee24f9095",
    "card_name": ""
  },
  {
    "uid": "047c69fa967380",
    "k0": "e27e286b7d56852682b23b025f78ec52",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "2ca46a24dac2adfd350a397c28ff63b5",
    "card_name": ""
  },
  {
    "uid": "048064fa967380",
    "k0": "0551da8255958bf63bdc3d1ee9e7f23c",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "3d59e2fce6e2c3faaefc151ad1d92f52",
    "card_name": ""
  },
  {
    "uid": "048069fa967380",
    "k0": "1ff2768a0243cd1668089cfe2be872d9",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "ea747b718fd58fdbf80140951223153b",
    "card_name": ""
  },
  {
    "uid": "048371fa967380",
    "k0": "680f406873d1c43412674dfa74eae5ee",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "eaebcc89d91a8a19c51f9ae10b2b2836",
    "card_name": ""
  },
  {
    "uid": "0484607a8f6980",
    "k0": "298e5c4b3a634f6831633ce89ad71439",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "da83b90bb251a5c5cb193521cf7b0511",
    "card_name": ""
  },
  {
    "uid": "048469fa967380",
    "k0": "b2aa317679530793fadf1b401df9eaae",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "cd2c3c5e4e5d9ccfba1b79a32f34a4a8",
    "card_name": ""
  },
  {
    "uid": "048a5bfa967380",
    "k0": "93d6ce5e81f9d10d3d09c8e34b831267",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "39d12337342832732917953dd4fa4c02",
    "card_name": ""
  },
  {
    "uid": "049062fa967380",
    "k0": "1208448ebce26784ab3a7a71920ad0cd",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "5d53aa93bffd6cd574ea17f5d8349d04",
    "card_name": ""
  },
  {
    "uid": "049064fa967380",
    "k0": "858a3a9c6be38164b837d4a3f673b6c0",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "8c5af52e0d6d1cf2b08a24c97fe31358",
    "card_name": ""
  },
  {
    "uid": "04915bfa967380",
    "k0": "fee3a3bc3f1b8ed0258d5901a6e3592c",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "5dab1a16abcb5d3cea45d406f830c110",
    "card_name": ""
  },
  {
    "uid": "049474fa967380",
    "k0": "87e30460ef84150cff03aeb81d24b44d",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "64c421bdd27be5f6f2d1dd87a80da18a",
    "card_name": ""
  },
  {
    "uid": "049564fa967380",
    "k0": "138f21f7be2e17694a47bb126c8a4707",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "f5aa2c117189528cd17a9961863df26e",
    "card_name": ""
  },
  {
    "uid": "049571fa967380",
    "k0": "fbe7eb7c32d414cb3baff3d5434a6667",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "648b60a2c7ec676e2212d426ff672d83",
    "card_name": ""
  },
  {
    "uid": "0496607a8f6980",
    "k0": "5e200d3d32e473a4a6ff827662254f58",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "96e2af96d1b635cf7a859578951d0887",
    "card_name": ""
  },
  {
    "uid": "049971fa967380",
    "k0": "15d23913f68712234f9f695af306609a",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "14f24a001ac44275421d9e76096667fc",
    "card_name": ""
  },
  {
    "uid": "049a74fa967380",
    "k0": "2453a5eacb0530424cdf6cc8604920d0",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "414ed4419ab24343a1b2d49c87b9a011",
    "card_name": ""
  },
  {
    "uid": "049c61fa967380",
    "k0": "5145e78f911f0d4aa4e8807a4f703b85",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "c1426d508c1604af92fc595362c7e75f",
    "card_name": ""
  },
  {
    "uid": "049c62fa967380",
    "k0": "bc5f970c586eb2d99def4db892665742",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "ab2878382a47615763eaa7243ca34f79",
    "card_name": ""
  },
  {
    "uid": "049c74fa967380",
    "k0": "40b675aff0846f06b8a4c4f79662030d",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "378291b2c283179f5fb01283e8d4db54",
    "card_name": ""
  },
  {
    "uid": "049e607a8f6980",
    "k0": "ec66b381c92e4aae534fc500fe40bfc6",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "7430240588663fac3dca78c5f626728b",
    "card_name": ""
  },
  {
    "uid": "049f5efa967380",
    "k0": "31af20e471f7310b6e02f1b6d8d00751",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "5ed9f23953c0eb7dd6fe242789050b91",
    "card_name": ""
  },
  {
    "uid": "049f607a8f6980",
    "k0": "1693f704dfa8ad8b6c40de9a843943fc",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "7e1ce1a8ca0f2a2b436e7720f1766d0c",
    "card_name": ""
  },
  {
    "uid": "049f71fa967380",
    "k0": "6f3f88690c8489cfa0c8e411cd1bad26",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "dfa1aff7741ac59e03df9b347685f060",
    "card_name": ""
  },
  {
    "uid": "04a164fa967380",
    "k0": "c2086d72df9947fbfd2d16eba5c021d2",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "76563eb0f2d6401ac240e3ba76baafcc",
    "card_name": ""
  },
  {
    "uid": "04a361fa967380",
    "k0": "979d95258d30d25ae01f214579290e40",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "0b4410763dbba0339fedaefb54a8c954",
    "card_name": ""
  },
  {
    "uid": "04a45efa967380",
    "k0": "c26202d2fb8493684138342e657f053f",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "c85291602d923163c1b2791a1a9c0068",
    "card_name": ""
  },
  {
    "uid": "04a469fa967380",
    "k0": "cbc36e3b201360a1add917ba3ec5a765",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "a228f4292217fbf5466d134707340bca",
    "card_name": ""
  },
  {
    "uid": "04a75efa967380",
    "k0": "aaad0ed98f2ed080a40d7c3ab3af40fd",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "e2ff83db667192087fb96af886b80170",
    "card_name": ""
  },
  {
    "uid": "04aa607a8f6980",
    "k0": "c56d22acc1c194c770e17f2c99d70318",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "461b3ef9f708c64c1118109b74efe926",
    "card_name": ""
  },
  {
    "uid": "04aa74fa967380",
    "k0": "dbad0a646432c0d5f56d709ed6fd06ec",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "f53f6cbbbe0ddc30983a5af88fb0cc56",
    "card_name": ""
  },
  {
    "uid": "04b0607a8f6980",
    "k0": "de43bf0e3e4684ffb90d5ed1e3cf49a5",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "991b93d0b8c8eee6492ac07935c5c323",
    "card_name": ""
  },
  {
    "uid": "04b074fa967380",
    "k0": "e9fdb2511ac9388d7faf3fa7a9b1bdf8",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "490864e99f93dc75b96ddf5af6acdbd9",
    "card_name": ""
  },
  {
    "uid": "04b260fa967380",
    "k0": "36c573087ce7d3bfd1e1a50ac40ea196",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "8de6ee427fe175d85bcbe2ff4c37b758",
    "card_name": ""
  },
  {
    "uid": "04b375fa967380",
    "k0": "f2d704d48fbaaccbfaf2407c1c2dcf4a",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "24b4bbf9b7d874f68c8d6c95431ac988",
    "card_name": ""
  },
  {
    "uid": "04b76efa967380",
    "k0": "b88d8182ef0cbfe5f7dd9f9d035adf76",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "43b53b3e52a3f75a0689f35a1ccaa6f5",
    "card_name": ""
  },
  {
    "uid": "04bd5bfa967380",
    "k0": "518660416867a699b1114caa4d827512",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "fa7773f506362d137e2f44e66267043a",
    "card_name": ""
  },
  {
    "uid": "04be75fa967380",
    "k0": "05b5941b508710fe870a127695d673d0",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "f25cd7040b576dfe18b5ae996fd4fa07",
    "card_name": ""
  },
  {
    "uid": "04bf5efa967380",
    "k0": "38a9b3fdffd530fdc50af8f88aeecd0f",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "5de3e2aaa1a2d8c2e96a6dfb59030865",
    "card_name": ""
  },
  {
    "uid": "04c375fa967380",
    "k0": "809e4663e72fa0cd2ba17bc626f20ebe",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "8004ca9b630aa48ecba07d066f9b5343",
    "card_name": ""
  },
  {
    "uid": "04c471fa967380",
    "k0": "18b983fb4e33645421d7a334f2c35794",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "506b30adda20ffbbf53f4eb9b9bf25e5",
    "card_name": ""
  },
  {
    "uid": "04c474fa967380",
    "k0": "ed42ca22f6cbdf30cc2296d45182de95",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "85b3bedf4e975b78132f0630d2176e93",
    "card_name": ""
  },
  {
    "uid": "04c56efa967380",
    "k0": "f52f5453c409b916743c53e82b4eba4b",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "b60bae939061f6c61806a822b51afecd",
    "card_name": ""
  },
  {
    "uid": "04c65efa967380",
    "k0": "6f1af0fc98e5e703b6dbdd8bdb8284a7",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "e58dddedbfda029817a69fbfb0fffdaf",
    "card_name": ""
  },
  {
    "uid": "04c75efa967380",
    "k0": "da8656d82a60d60687e2e0a5216d5742",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "5b7ebae57316525149f39d354e453907",
    "card_name": ""
  },
  {
    "uid": "04a1879ac11390",
    "k0": "edbb20b06dc2e6c5d7b7efeb3309d0c3",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "2fda32e3af129c963064b07106da5abb",
    "card_name": ""
  },
  {
    "uid": "04c15ffa967380",
    "k0": "92560282b10ffa655e3e137f42ffd9a8",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "d05a7d5d9ed40418041543537930aaeb",
    "card_name": ""
  },
  {
    "uid": "04c074fa967380",
    "k0": "d952500db8a87731b43a8511ca492bea",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "584fafb7ec06cf371abaa33e2ca9f44c",
    "card_name": ""
  },
  {
    "uid": "045162fa967380",
    "k0": "edd70fda475f214f79f6ba195e86b9ea",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "590856aad9b22a80264a1bb58c52d042",
    "card_name": ""
  },
  {
    "uid": "04b26efa967380",
    "k0": "24185441eaa980e90cab91a99ba9115e",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "b897af57df781c60a34bab9163862ba7",
    "card_name": ""
  },
  {
    "uid": "044462fa967380",
    "k0": "918bae01ad5f1c520a9efe3df1e6eab2",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "744899522e28dabb3514ce0bef8770a2",
    "card_name": ""
  },
  {
    "uid": "046e607a8f6980",
    "k0": "c583531958ec701f7bd857d6d3f0adfa",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "2564c25c702de6c6881f009d95e3faed",
    "card_name": ""
  },
  {
    "uid": "04b663fa967380",
    "k0": "c7179197837d974fe12209c09b477bdc",
    "k1": "3db8852a71d11fa0adb6babaf274af89",
    "k2": "fd8347e410af9667307033c8ee307309",
    "card_name": ""
  }
];
