/**
 * scripts/build_keys.js — Deploy-time CSV → JS bundler
 *
 * Reads keys/*.csv and generates utils/generatedKeyData.js
 * with static JS constants. Run before `wrangler deploy`.
 *
 * Usage: node scripts/build_keys.js
 */

import { readFileSync, readdirSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const KEYS_DIR = join(ROOT, "keys");
const OUTPUT = join(ROOT, "utils", "generatedKeyData.js");

function parseCsvLines(text) {
  return text
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith("#"));
}

function parseIssuerKeyCsv(text) {
  const lines = parseCsvLines(text);
  return lines.slice(1).map((line) => {
    const [hex, label] = line.split(",");
    return { hex: hex.trim().toLowerCase(), label: label?.trim() || hex.slice(0, 8) };
  });
}

function parsePerCardCsv(text) {
  const lines = parseCsvLines(text);
  return lines.slice(1).map((line) => {
    const [uid, k0, k1, k2, card_name] = line.split(",");
    return {
      uid: uid.trim().toLowerCase(),
      k0: k0.trim().toLowerCase(),
      k1: k1.trim().toLowerCase(),
      k2: k2.trim().toLowerCase(),
      card_name: card_name?.trim() || "",
    };
  });
}

function isIssuerKeyFile(name) {
  return name.endsWith(".csv") && !name.startsWith("_percard");
}

function isPerCardFile(name) {
  return name.endsWith(".csv") && name.startsWith("_percard");
}

function domainFromFilename(name) {
  // boltcardpoc.psbt.me.csv → boltcardpoc.psbt.me
  // _default.csv → _default
  return name.replace(/\.csv$/, "");
}

function main() {
  const files = readdirSync(KEYS_DIR).filter((f) => f.endsWith(".csv")).sort();

  const issuerKeysByDomain = {};
  const perCardKeys = [];

  for (const file of files) {
    const text = readFileSync(join(KEYS_DIR, file), "utf-8");
    const domain = domainFromFilename(file);

    if (isIssuerKeyFile(file)) {
      issuerKeysByDomain[domain] = parseIssuerKeyCsv(text);
    } else if (isPerCardFile(file)) {
      perCardKeys.push(...parsePerCardCsv(text));
    }
  }

  const output = [
    "// AUTO-GENERATED by scripts/build_keys.js — DO NOT EDIT",
    "// Source: keys/*.csv",
    "// Regenerate: node scripts/build_keys.js",
    "",
    `export const ISSUER_KEYS_BY_DOMAIN = ${JSON.stringify(issuerKeysByDomain, null, 2)};`,
    "",
    `export const PERCARD_KEYS = ${JSON.stringify(perCardKeys, null, 2)};`,
    "",
  ].join("\n");

  writeFileSync(OUTPUT, output, "utf-8");

  const domainCount = Object.keys(issuerKeysByDomain).length;
  const issuerKeyCount = Object.values(issuerKeysByDomain).flat().length;
  const perCardCount = perCardKeys.length;
  console.log(`Generated ${OUTPUT}`);
  console.log(`  Domains: ${domainCount}, Issuer keys: ${issuerKeyCount}, Per-card keys: ${perCardCount}`);
}

main();
