name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to latest version

      # Step 2: Set up Node.js (version 18)
      - name: Set up Node.js
        uses: actions/setup-node@v4  # Updated to latest version
        with:
          node-version: '18'
          cache: 'npm'  # Caches dependencies for faster installs

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Clear Jest cache
      - name: Clear Jest cache
        run: npx jest --clearCache

      # Step 5: Run Jest tests
      - name: Run Jest tests
        run: npm test

      # Step 6: Upload Jest Test Results (fixed)
      - name: Upload Jest Test Results
        uses: actions/upload-artifact@v4  # Updated from v3 to v4
        with:
          name: jest-results
          path: test-results.json
          retention-days: 5
